### PR TITLE
added splitAt for strings

### PR DESCRIPTION
**Pull request by jessekelly881**
Convert a string into a Tuple by splitting it at an index.  Example:

```javascript
import * as t from "fp-ts/Tuple";
import { flow } from "fp-ts/function";
import { partitionAtIndex } from "fp-ts-std/String"

const capitalize = flow(
  partitionAtIndex(1),
  t.bimap(s.toLower, s.toUpper), // snd, first
  ([ x, y ]) => x + y
);
```

### CODE REVIEW

**Comment by samhh** [comment]
Thanks for your contribution!

I think for [consistency](https://gcanti.github.io/fp-ts/modules/Array.ts.html#splitat) we ought to call this function `splitAt`. It looks like the same function specialised in a sense to strings:

```ts
> import * as A from 'fp-ts/Array'
> A.splitAt(1)(['a', 'b', 'c'])
[ [ 'a' ], [ 'b', 'c' ] ]
```

**Comment by jessekelly881** [comment]
Hmm. This is a good point. Maybe it makes more sense to rename this function and then try to merge it into fp-ts directly.

**Comment by samhh** [comment]
I'll incorporate it here but certainly feel free to take it upstream as well. I remove stuff from fp-ts-std as and when it appears in fp-ts but there's value in having it here in the meantime.

Thanks again!

**Comment by jessekelly881** [comment]
Sounds good! Thanks for the feedback! I will send it upstream to fp-ts as well.

**Pull request merged**
