### PR TITLE
fromString & floatFromString

### PR DESCRIPTION
**Pull request by anthonyjoeseph**
Closes https://github.com/samhh/fp-ts-std/issues/43

### CODE REVIEW

**Review by samhh — CHANGES_REQUESTED** [review]
Something I've been trying to keep consistent is that everything is curried to enable easy partial application. In this case that probably means taking the radix first as `Option<number>` and then returning the rest as a function.

It might be cleaner to separate these into two distinct functions, one of which takes a radix and one which does not (and uses a default of `10` probably?).

**Comment by anthonyjoeseph** [comment]
How does it look now?

**Review by samhh — APPROVED** [review]

**Comment by samhh** [comment]
Looking good!

Per CI there's probably a small issue with the documentation following this change, you can run `yarn docs` to diagnose.

Also totally optional, but if you haven't worked with property-based tests before this'd be a great opportunity; it should be possible to test these functions more thoroughly by first generating valid numbers (see `fast-check`), then converting them to strings, then converting them back again and checking the output. :slightly_smiling_face:

**Comment by samhh** [comment]
Looking great, thanks for your contribution :+1: 

I've raised an issue to investigate the date tests [here](https://github.com/samhh/fp-ts-std/issues/45), thanks for the heads up.

**Pull request merged**
