### PR TITLE
chore(ci):  test against all available node versions

### PR DESCRIPTION
**Pull request by waynevanson**
`replaceAll` doesn't exist in node >14.

Remove the first commit made here `02b08c2` as proof.

### CODE REVIEW

**Comment by samhh** [comment]
I haven't put much thought into engine support until now. It should certainly be formalised.

Should this be the responsibility of the library or the consumer? The consumer could use a [shim](https://github.com/es-shims/String.prototype.replaceAll) which will presumably be much more robust.

**Comment by waynevanson** [comment]
I think for Node LTS it shouldn't be a hassle. Version 14 is still the LTS so it should be prioritised.
Someone is going to come along and make an issue about it anyway so it's not worth the hassle of trying to avoid fixing the issue, when the solution is in our hands.

By not supporting the change, we're saying that only node 15+ is supported, which doesn't seem correct.

**Comment by samhh** [comment]
In principle I agree with supporting Node LTS, however I'm concerned about how much more complex the linked shim looks. Are we _very_ confident this doesn't introduce any obscure regressions?

**Comment by waynevanson** [comment]
> I'm concerned about how much more complex the linked shim looks

That's a good point, but I'm unsure. [The beef of the implementation](https://github.com/es-shims/String.prototype.replaceAll/blob/main/implementation.js) is ES3 compatible which might be the reason for the complexity.

The tsconfig targets esnext, which may have also been the reason we have to make this change too, which I hadn't considered. Should it be es6 or es5 instead?

**Comment by waynevanson** [comment]
You're right, just checked with ts repl.

**Comment by imcotton** [comment]
How about ([playground]):
```ts
// @lib: es2021
// @target: es2019

const replaceAll = (r: string) => (s: string) => (x: string) =>
    x.replaceAll?.(r, s) ?? x.replace(new RegExp(r, "g"), s)
```

note: by targeting **tsc** to **2019** will emit shim for [optional chaining][ocwfc] and [nullish coalescing][oco] which to me is reasonable trade-off to have Node.js **v12** covered at the moment.


[ocwfc]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining#optional_chaining_with_function_calls
[oco]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator

[playground]: https://www.typescriptlang.org/play?target=6&jsx=0&lib=lib.es2021.d.ts&ts=4.5.3#code/PTAEAEBsEsCMC5QFMDOAmADGgjAKBBAC4CGATgOZKGKqbYCcuuAxgPYB2KhopSADpGLMkAQUiRQAXlAAKUoi6lo7cgEopAPlkoFhJSvWStMgB679azblA3QJgHS8BQ0eID89uQBpQKdW7c7R35BYRl2JAB3UAAlJHIAURM+b1AAInI01R8-JiA

**Comment by samhh** [comment]
Let's formalise support for LTS Node, which for another few months includes Node v12. Thanks for your input both!

There are some conflicts here, and some difficulties in CI with coverage detection, so I've raised a new PR that's mostly the same: https://github.com/samhh/fp-ts-std/pull/102

**Pull request closed without merging**
