### PR TITLE
Revamp build system

### LINKED ISSUE #113: `eslint-plugin-import/no-unresolved` error caused by conditional exports
Hi @samhh, thank you for your work. I'm aware of the [pinned issue](https://github.com/samhh/fp-ts-std/issues/89) that discusses the interaction between `jest` and `fp-ts-std`'s conditional exports. I'm having a similar issue with the [import plugin](import-js/eslint-plugin-import) for eslint. The `import/no-unresolved` rule complains that it is `unable to resolve path to module 'fp-ts-std/Array`.

[This issue](https://github.com/import-js/eslint-plugin-import/issues/2357) discusses ways to mitigate the problem. Would you consider applying the same recommendations here?

Thank you!

### PR DESCRIPTION
**Pull request by andreavaccari**
Closes #113 and #118

### CODE REVIEW

**Comment by andreavaccari** [comment]
@samhh anything I can do to help get this merged?

**Comment by samhh** [comment]
Hey @andreavaccari! Sorry for my slow follow up, I've been mostly AFK the last few weeks.

It would be helpful for me to know what exactly tsup is doing differently under the hood. On the plus side it's _very_ tempting for me to offload all this bundling stuff to a third party like this... :wink:

**Comment by samhh** [comment]
Closing as stale. Happy to revisit if there's interest.

**Comment by samhh** [comment]
Closing as stale. Happy to revisit if there's interest.

**Pull request closed without merging**
